### PR TITLE
Make the git hook platform agnostic

### LINKED ISSUE #5: Support Windows

### PR DESCRIPTION
**Pull request by eupn**
Resolves #5, I think.

What has been done in this PR::
* Conditional compilation check with `#[cfg(windows)]` for Windows

### CODE REVIEW

**Comment by eupn** [comment]
Not working on Windows 😢, will try to figure out why.

**Comment by tserivdd** [comment]
@eupn wait, who's on Windows? Windows is not allowed! haha!

**Comment by workflow** [comment]
> Not working on Windows cry, will try to figure out why.
> 
> UPD: probably due to `/` slashes in `HOOK_PATH`. Probably one should construct a path by using portable `join` function.

Well shave me belly with a rusty razor! Ok if we add that to this PR? Otherwise thar's not much added value, imho...

**Comment by eupn** [comment]
>Ok if we add that to this PR?

That's what I meant to do!

**Comment by eupn** [comment]
Alas, git for windows doesn't support executables as hooks, only "shell" (stripped version of `sh`) scripts 😢.

Sources:
- https://www.tygertec.com/git-hooks-practical-uses-windows/
- https://stackoverflow.com/a/57015149

Have to revert some of the changes.

**Comment by ebkalderon** [comment]
@eupn I've retriggered all of the CI checks since it seems that the Rust 1.37 macOS check got stuck on the setup process and timed out. Hopefully everything will pass CI this time!

**Pull request merged**
